### ISSUE TITLE
bug: support Factorio 2.x (Space Age DLC)

### ISSUE THREAD

**Issue by Kariton** [nekomeowww/factorio-rcon-api#2] opened 2024-10-28 13:40 UTC
i understand that this is still an early stage and you even referenced the docker release as "unstable". :)
IMO this is such a huge addition i cant imagine why there is no other project like yours!
only found [DirkHeinke/factorio-constant-combinator-rest-api](https://github.com/DirkHeinke/factorio-constant-combinator-rest-api).

after tinkering with the API i found a few things:

is the default dict element `{"username":"Players","online":false}` a bug or a feature?
```sh
# curl -X GET http://factorio/api/v1/factorio/console/command/players
{"players":[{"username":"Players","online":false},{"username":"MYNAME","online":true}]}
```

save does return nothing?
```sh
# curl -X POST http://factorio/api/v1/factorio/console/command/server-save
{}
```

after leaving the server:
```sh
# curl -X GET http://factorio/api/v1/factorio/console/command/players
{"errors":[{"id":"BAD_REQUEST","status":400,"code":"BAD_REQUEST","title":"Bad Request","detail":"failed to parse admins: MYNAME due to parts not equals 2"}]}
```

**Comment by Kariton** [comment] 2024-10-28 19:02
message multiline support seems to be missing:

```sh
# evolution_value=$(curl -s -X GET https://factorio/api/v1/factorio/console/command/evolution | jq -r | sed 's/"/\\"/g')
# echo "${evolution_value}"
{
  \"evolutionFactor\": 0.8879,
  \"time\": 12,
  \"pollution\": 76,
  \"spawnerKills\": 12
}
# curl -X POST https://factorio/api/v1/factorio/console/command/message -d "{\"message\": \"${evolution_value}\"}"
{"errors":[{"id":"INVALID_ARGUMENT","status":400,"code":"INVALID_ARGUMENT","title":"Invalid Argument","detail":"invalid character '\\n' in string literal"}]}
```

```sh
# export evolution_value=$(curl -s -X GET https://factorio/api/v1/factorio/console/command/evolution | sed 's/"/\\"/g')
# echo "${evolution_value}"
{\"evolutionFactor\":0.8879,\"time\":12,\"pollution\":76,\"spawnerKills\":12}
# curl -X POST https://factorio.prod.k8s.interwebs.space/api/v1/factorio/console/command/message -d "{\"message\": \"${evolution_value}\"}"
{}
```

**Comment by nekomeowww** [comment] 2024-10-29 16:55
Thanks for posting and give it a try.

> # curl -X POST http://factorio/api/v1/factorio/console/command/server-save
> {}

expected. I used `grpc-gateway` to wrap the API for simplicity, and in protobufs world, we dont usually return the more commonly used `{"code": <some ok number or string>, "message": "ok", "data": true}` pattern for the API. So, don't panic, this is expected. If you need the types for other languages or other third party tools like TypeScript or Python, you can generate your own SDK from the protobufs files in the project directory under `apis/`

> # curl -X GET http://factorio/api/v1/factorio/console/command/players

- What game version are you on? It seems the player list is no longer compatible, possibly caused by the new released DLC, but I am still in travel, haven't tried it, therefore the newest version, yes, may not work well.

> curl -X GET http://factorio/api/v1/factorio/console/command/whitelist

Same as last one. Can you provide me a in game output?

> # curl -X GET https://factorio/api/v1/factorio/console/command/time

Same, should caused by incompatible game output.

> # evolution_value=$(curl -s -X GET https://factorio/api/v1/factorio/console/command/evolution | jq -r | sed 's/"/\\"/g')
> # echo "${evolution_value}"
> {
>  \"evolutionFactor\": 0.8879,
>  \"time\": 12,
>  \"pollution\": 76,
>  \"spawnerKills\": 12
> }

Interesting use case, haven't tested this actually, will need to investigate but I guess this might be a `wontfix` one.

**Comment by Kariton** [comment] 2024-10-30 01:14
Hey,

yes, i am on the current 2.0 release. 2.0.12 by now.
```sh
# curl -X GET https://factorio.prod.k8s.interwebs.space/api/v1/factorio/console/command/version
{"version":"2.0.12"}
```

might be the issue.
yesterday i remembered that your repo is older then the current lease... but wasnt able to comment that. :)

thanks for your brief explanation about the "empty" returned values.
enjoy your vacation and have nice last days on your trip!

**Comment by nekomeowww** [comment] 2024-10-31 02:30
Let me quickly bootstrap a new server to test this.

**Closed** 2024-10-31 17:58 UTC
Labels: bug
